# Generated by Django 4.2.6 on 2023-11-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('piso', models.IntegerField()),
                ('depto', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
    ]
