# Generated by Django 4.2.6 on 2023-11-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPFinal', '0009_alter_departamento_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='imagen',
        ),
    ]
